"""Runtime configuration model shared by capture, STT, VAD, translation, and overlay modules."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

@dataclass
class RuntimeConfig:
    model_size: str = 'small'
    model_device: str = 'cuda'
    compute_type: str = 'float16'
    stt_provider: str = 'whisper'
    stt_variant: str = 'auto'
    stt_auto_download: bool = True
    stt_model_path: str = ''
    whisperx_enable_phoneme_asr: bool = True
    whisperx_enable_forced_alignment: bool = True
    whisperx_enable_vad: bool = True
    whisperx_vad_method: str = 'silero-vad'
    whisperx_enable_diarization: bool = False
    whisperx_alignment_model: str = ''
    whisperx_alignment_language: str = 'auto'
    whisperx_diarization_model: str = 'pyannote/speaker-diarization-3.1'
    whisperx_hf_token: str = ''
    cpu_fallback_on_cuda_error: bool = True
    cuda_compat_source_dll: str = 'D:\\CUDA\\bin\\x64\\cublas64_13.dll'
    ffmpeg_dll_dir: str = 'D:\\FFmpeg\\ffmpeg-7.1.1-full_build-shared\\bin'
    segment_seconds: float = 6.0
    hop_seconds: float = 1.5
    source_language: Optional[str] = None
    cjk_no_space_gap_seconds: float = 0.2
    source_mode: str = 'loopback'
    ui_language: str = 'zh'
    source_device_indices: list[int] = field(default_factory=list)
    source_mix_weights: list[float] = field(default_factory=list)
    source_app_name: str = ''
    source_app_names: list[str] = field(default_factory=list)
    source_channel_mode: str = 'mono'
    overlap_merge_method: str = 'stable-tail'
    preprocess_enabled: bool = True
    preprocess_modules: str = 'auto'
    vad_enabled: bool = True
    vad_backend: str = 'silero'
    vad_rms_threshold: float = 0.008
    vad_adaptive_enabled: bool = True
    vad_adaptive_min_threshold: float = 0.004
    vad_adaptive_max_threshold: float = 0.08
    vad_adaptive_noise_multiplier: float = 2.6
    vad_adaptive_margin: float = 0.002
    whisper_max_context: Optional[int] = None
    whisper_entropy_thold: Optional[float] = None
    whisper_logprob_thold: Optional[float] = None
    whisper_no_speech_thold: Optional[float] = None
    whisper_temperature: Optional[float] = None
    whisper_beam_size: Optional[int] = None
    whisper_best_of: Optional[int] = None
    max_lines: int = 10
    overlay_width: int = 1200
    overlay_height: int = 320
    overlay_x: int = 40
    overlay_y: int = 700
    overlay_opacity: float = 0.8
    font_size: int = 18
    text_color: str = '#F0F2F5'
    source_text_color: str = '#F0F2F5'
    translated_text_color: str = '#FFD98A'
    status_color: str = '#78D7FF'
    error_color: str = '#FF7878'
    background_color: str = '#0A101A'
    translation_enabled: bool = False
    translation_from: str = 'auto'
    translation_to: str = 'zh'
    bilingual_style: str = 'stacked'
    device_index: Optional[int] = None
    log_dir: str = 'logs'
    debug_mode: bool = False

